// Load the Ploigos Jenkins Library
library identifier: 'ploigos-jenkins-library@v0.19.1',
retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/ploigos/ploigos-jenkins-library.git'
])

// run the pipeline
ploigosWorkflowEverything(
    stepRunnerConfigDir: 'cicd/ploigos-integration-environment/jenkins/everything/ploigos-step-runner-config/',

    pgpKeysSecretName: 'pgp-keys-ploigos-workflow-ref-quarkus-mvn-jenkins-eve-fruit',
    workflowServiceAccountName: 'ploigos-workflow-ref-quarkus-mvn-jenkins-eve-fruit',

    workflowWorkerImageDefault: 'ploigos/ploigos-base:v0.19.1',
    workflowWorkerImageAgent: 'ploigos/ploigos-ci-agent-jenkins:v0.19.1',
    workflowWorkerImageUnitTest: 'ploigos/ploigos-tool-maven:v0.19.1',
    workflowWorkerImagePackage: 'ploigos/ploigos-tool-maven:v0.19.1',
    workflowWorkerImageStaticCodeAnalysis: 'ploigos/ploigos-tool-sonar:v0.19.1',
    workflowWorkerImagePushArtifacts: 'ploigos/ploigos-tool-maven:v0.19.1',
    workflowWorkerImageContainerOperations: 'ploigos/ploigos-tool-containers:v0.19.1',
    workflowWorkerImageContainerImageStaticComplianceScan: 'ploigos/ploigos-tool-openscap:v0.19.1',
    workflowWorkerImageContainerImageStaticVulnerabilityScan: 'ploigos/ploigos-tool-openscap:v0.19.1',
    workflowWorkerImageDeploy: 'ploigos/ploigos-tool-argocd:v0.19.1',
    workflowWorkerImageValidateEnvironmentConfiguration: 'ploigos/ploigos-tool-config-lint:v0.19.1',
    workflowWorkerImageUAT: 'ploigos/ploigos-tool-maven:v0.19.1',
    workflowWorkerImageAutomatedGovernance: 'ploigos/ploigos-tool-autogov:v0.19.1',

    workflowWorkersImagePullPolicy: 'IfNotPresent',
    stepRunnerUpdateLibrary: false,
    stepRunnerLibSourceUrl: 'git+https://github.com/ploigos/ploigos-step-runner.git@v0.19.1'
)
