// Load the Ploigos Jenkins Library
library identifier: 'ploigos-jenkins-library@v0.22.0',
retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/ploigos/ploigos-jenkins-library.git'
])

// run the pipeline
ploigosWorkflowEverything(
    stepRunnerConfigDir: 'cicd/ploigos-integration-environment/jenkins/everything/ploigos-step-runner-config/',

    pgpKeysSecretName: 'pgp-keys-ploigos-workflow-ref-quarkus-mvn-jenkins-eve-fruit',
    workflowServiceAccountName: 'ploigos-workflow-ref-quarkus-mvn-jenkins-eve-fruit',

    workflowWorkerImageDefault: 'ploigos/ploigos-tool-maven:nightly',
    workflowWorkerImageAgent: 'ploigos/ploigos-ci-agent-jenkins:nightly',
    workflowWorkerImageUnitTest: 'ploigos/ploigos-tool-maven:nightly',
    workflowWorkerImagePackage: 'ploigos/ploigos-tool-maven:nightly',
    workflowWorkerImageStaticCodeAnalysis: 'ploigos/ploigos-tool-sonar:nightly',
    workflowWorkerImagePushArtifacts: 'ploigos/ploigos-tool-maven:nightly',
    workflowWorkerImageContainerOperations: 'ploigos/ploigos-tool-containers:nightly',
    workflowWorkerImageContainerImageStaticComplianceScan: 'ploigos/ploigos-tool-openscap:nightly',
    workflowWorkerImageContainerImageStaticVulnerabilityScan: 'ploigos/ploigos-tool-openscap:nightly',
    workflowWorkerImageDeploy: 'ploigos/ploigos-tool-argocd:nightly',
    workflowWorkerImageValidateEnvironmentConfiguration: 'ploigos/ploigos-tool-config-lint:nightly',
    workflowWorkerImageUAT: 'ploigos/ploigos-tool-maven:nightly',
    workflowWorkerImageAutomatedGovernance: 'ploigos/ploigos-tool-autogov:nightly',

    stepRunnerUpdateLibrary: 'true',
    stepRunnerLibSourceUrl: 'git+https://github.com/ploigos/ploigos-step-runner.git@main',
)
