// Load the Ploigos Jenkins Library
library identifier: 'ploigos-jenkins-library@v0.17.0',
retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/ploigos/ploigos-jenkins-library.git'
])

// run the pipeline
ploigosWorkflowMinimal(
    stepRunnerConfigDir: 'cicd/jenkins/minimal/ploigos-step-runner-config/',
    pgpKeysSecretName: 'pgp-keys-ploigos-workflow-ref-quarkus-mvn-jenkins-std-fruit',

    workflowServiceAccountName: 'ploigos-workflow-ref-quarkus-mvn-jenkins-std-fruit',

    workflowWorkerImageDefault: 'ploigos/ploigos-ci-agent-jenkins:v0.17.0',
    workflowWorkerImagePackage: 'ploigos/ploigos-tool-maven:v0.17.0',
    workflowWorkerImageContainerOperations: 'ploigos/ploigos-tool-containers:v0.17.0',
    workflowWorkerImageDeploy: 'ploigos/ploigos-tool-argocd:v0.17.0'
)
