// Load the Ploigos Jenkins Library
library identifier: 'ploigos-jenkins-library@v0.22.0',
retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/ploigos/ploigos-jenkins-library.git'
])

// run the pipeline
ploigosWorkflowTypical(
    stepRunnerConfigDir: 'cicd/ploigos-software-factory-operator/ploigos-step-runner-config/',

    pgpKeysSecretName: 'ploigos-gpg-key',
    workflowServiceAccountName: 'jenkins',

    workflowWorkerImageDefault: 'quay.io/ploigos/ploigos-tool-maven:v1.0.0',
    workflowWorkerImageAgent: 'quay.io/ploigos/ploigos-ci-agent-jenkins:v1.0.0',
    workflowWorkerImageUnitTest: 'quay.io/ploigos/ploigos-tool-maven:v1.0.0',
    workflowWorkerImagePackage: 'quay.io/ploigos/ploigos-tool-maven:v1.0.0',
    workflowWorkerImageStaticCodeAnalysis: 'quay.io/ploigos/ploigos-tool-sonar:v1.0.0',
    workflowWorkerImagePushArtifacts: 'quay.io/ploigos/ploigos-tool-maven:v1.0.0',
    workflowWorkerImageContainerOperations: 'quay.io/ploigos/ploigos-tool-containers:v1.0.0',
    workflowWorkerImageContainerImageStaticVulnerabilityScan: 'quay.io/ploigos/ploigos-tool-openscap:v1.0.0',
    workflowWorkerImageDeploy: 'quay.io/ploigos/ploigos-tool-argocd:v1.0.0',
    workflowWorkerImageUAT: 'quay.io/ploigos/ploigos-tool-maven:v1.0.0',

    separatePlatformConfig: true
)
