// Load the Ploigos Jenkins Library
library identifier: 'ploigos-jenkins-library@feature/everything-refactor',
retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/itewk/ploigos-jenkins-library.git'
])

// run the pipeline
ploigosWorkflowTypical(
    stepRunnerConfigDir: 'cicd/ploigos-step-runner-config/',
    pgpKeysSecretName: 'pgp-keys-ploigos-workflow-ref-quarkus-mvn-jenkins-std-fruit',

    workflowServiceAccountName: 'ploigos-workflow-ref-quarkus-mvn-jenkins-std-fruit',

    workflowWorkerImageDefault: 'ploigos/ploigos-ci-agent-jenkins:edge',
    workflowWorkerImageUnitTest: 'ploigos/ploigos-tool-maven:edge',
    workflowWorkerImagePackage: 'ploigos/ploigos-tool-maven:edge',
    workflowWorkerImageStaticCodeAnalysis: 'ploigos/ploigos-tool-sonar:edge',
    workflowWorkerImagePushArtifacts: 'ploigos/ploigos-tool-maven:edge',
    workflowWorkerImageContainerOperations: 'ploigos/ploigos-tool-containers:edge',
    workflowWorkerImageContainerImageStaticVulnerabilityScan: 'ploigos/ploigos-tool-openscap:edge',
    workflowWorkerImageDeploy: 'ploigos/ploigos-tool-argocd:edge',
    workflowWorkerImageUAT: 'ploigos/ploigos-tool-maven:edge',

    stepRunnerUpdateLibrary: true,
    stepRunnerLibSourceUrl: 'git+https://github.com/itewk/ploigos-step-runner.git@feature/buildah-defaults',
    workflowWorkersImagePullPolicy: 'Always'
)
