// Load the Ploigos Jenkins Library
library identifier: 'ploigos-jenkins-library@main',
retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/ploigos/ploigos-jenkins-library.git'
])

// run the pipeline
ploigosWorkflowMinimal(
    stepRunnerConfigDir: 'cicd/ploigos-integration-environment/jenkins/minimal/ploigos-step-runner-config/',

    pgpKeysSecretName: 'pgp-keys-ploigos-workflow-ref-quarkus-mvn-jenkins-min-fruit',
    workflowServiceAccountName: 'ploigos-workflow-ref-quarkus-mvn-jenkins-min-fruit',

    workflowWorkerImageDefault: 'ploigos/ploigos-base:edge',
    workflowWorkerImageAgent: 'ploigos/ploigos-ci-agent-jenkins:edge',
    workflowWorkerImagePackage: 'ploigos/ploigos-tool-maven:edge',
    workflowWorkerImageContainerOperations: 'ploigos/ploigos-tool-containers:edge',
    workflowWorkerImageDeploy: 'ploigos/ploigos-tool-argocd:edge',

    workflowWorkersImagePullPolicy: 'Always',
    stepRunnerUpdateLibrary: true,
    stepRunnerLibSourceUrl: 'git+https://github.com/ploigos/ploigos-step-runner.git@main'
)
