// Load the Ploigos Jenkins Library
library identifier: 'ploigos-jenkins-library@main',
retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/ploigos/ploigos-jenkins-library.git'
])

// run the pipeline
ploigosWorkflowTypical(
    stepRunnerConfigDir: 'cicd/jenkins/typical/ploigos-step-runner-config/',

    pgpKeysSecretName: 'pgp-keys-ploigos-workflow-ref-quarkus-mvn-jenkins-typ-fruit',
    workflowServiceAccountName: 'ploigos-workflow-ref-quarkus-mvn-jenkins-typ-fruit',

    workflowWorkerImageDefault: 'ploigos/ploigos-ci-agent-jenkins:pr-69',
    workflowWorkerImageUnitTest: 'ploigos/ploigos-tool-maven:pr-69',
    workflowWorkerImagePackage: 'ploigos/ploigos-tool-maven:pr-69',
    workflowWorkerImageStaticCodeAnalysis: 'ploigos/ploigos-tool-sonar:pr-69',
    workflowWorkerImagePushArtifacts: 'ploigos/ploigos-tool-maven:pr-69',
    workflowWorkerImageContainerOperations: 'ploigos/ploigos-tool-containers:pr-69',
    workflowWorkerImageContainerImageStaticVulnerabilityScan: 'ploigos/ploigos-tool-openscap:pr-69',
    workflowWorkerImageDeploy: 'ploigos/ploigos-tool-argocd:pr-69',
    workflowWorkerImageUAT: 'ploigos/ploigos-tool-maven:pr-69'
)
