// Load the Ploigos Jenkins Library
library identifier: 'ploigos-jenkins-library@feature/params-refactor',
retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/itewk/ploigos-jenkins-library.git'
])

// run the pipeline
java11ServicePloigosWorkflowTypical(
    stepRunnerConfigDir: 'cicd/ploigos-integration-environment/jenkins/typical/ploigos-step-runner-config/',

    pgpKeysSecretName: 'pgp-keys-ploigos-workflow-ref-quarkus-mvn-jenkins-typ-fruit',
    workflowServiceAccountName: 'ploigos-workflow-ref-quarkus-mvn-jenkins-typ-fruit',

    // TEMP TEST
    platformConfigConfigMapName: 'ploigos-platform-config-ian-test1',
    platformConfigSecretName: 'ploigos-platform-config-secrets-ian-test1'
)
